#ifndef QUICK_CLEANUP_OFFSETS_H
#define QUICK_CLEANUP_OFFSETS_H

#define RVA_HOUSE_STATUS_UI_SETUP 0x001DDC50ULL // HouseStatusUI setup/refresh routine, (Hook point after the game builds the House status UI)...
#define HOUSE_STATUS_UI_SETUP_STOLEN_BYTES 20 // Bytes overwritten by the HouseStatusUI setup hook trampoline...

#define RVA_HOUSE_BUTTON_ACTIVATE 0x0096E4E0ULL // HouseButton activation/click handler, hook point used to intercept the custom cleanup button...
#define HOUSE_BUTTON_ACTIVATE_STOLEN_BYTES 15 // Bytes overwritten by the HouseButton activation hook trampoline...

#define RVA_HOUSE_BUTTON_CAN_ACTIVATE 0x0096E6F0ULL // HouseButton interactability gate used before activation; CatStats/CatMenu modal blockers make this return false...
#define HOUSE_BUTTON_CAN_ACTIVATE_STOLEN_BYTES 15 // Bytes overwritten by the HouseButton interactability hook trampoline...

#define RVA_UI_FIND_CHILD_BY_NAME 0x000E7370ULL // UI node tree helper that returns a child node by its NarrowString name...
#define RVA_CONTEXT_FROM_MANAGER 0x0095AFE0ULL // Scene/manager helper that returns the component context used for component refs...
#define RVA_ALLOC_COMPONENT_FROM_TYPE 0x009590C0ULL // Engine allocator that creates component instance from type descriptor...
#define RVA_HOUSE_BUTTON_CONSTRUCT 0x001411A0ULL // HouseButton constructor/initializer called after raw component allocation...
#define RVA_SCENE_REGISTER_COMPONENT 0x0095AF40ULL // Scene manager registration routine that attaches a new component to the scene...
#define RVA_RESIZE_PTR_ARRAY 0x00D3CF88ULL // Runtime realloc-like helper used by engine POD pointer arrays when growing component lists...
#define RVA_CONTEXT_ATTACH_COMPONENT_REF 0x00047B60ULL // Context helper that records a component reference in the current scene context...
#define RVA_HOUSE_BUTTON_SETUP_FROM_NODE 0x0096DDF0ULL // HouseButton setup routine that binds the component to its UI node and label key...
#define RVA_ASSIGN_GAME_STRING_LITERAL 0x00051C20ULL // Narrow game-string assignment from a literal buffer and explicit length...
#define RVA_INIT_NARROW_STRING 0x00052640ULL // NarrowString constructor/initializer from a null-terminated literal...
#define RVA_DESTROY_NARROW_STRING 0x000522D0ULL // NarrowString destructor/free routine for possible heap-backed strings...
#define RVA_LOCALIZE_NARROW_KEY 0x00956270ULL // Localization lookup that converts a narrow localization key to a WideString result...
#define RVA_ASSIGN_WIDE_GAME_STRING 0x000623C0ULL // Wide game-string assignment used by HouseButton label text...
#define RVA_DESTROY_WIDE_GAME_STRING 0x00051DE0ULL // WideString destructor/free routine for possible heap-backed localized strings...
#define RVA_POP_POO_PICKUP 0x002ED220ULL // Pickup cleanup routine for poop pickup components, plays the game's normal pop/remove path...
#define RVA_HOUSE_CAT_IS_ALIVE 0x001FC550ULL // Returns whether the scene HouseCat is currently alive...
#define RVA_HOUSE_CAT_TEARDOWN 0x001FCF20ULL // HouseCat teardown routine, used to remove dead cat scene objects via the game's own cleanup path...
#define RVA_GLOBAL_PROGRESSION_ADD_NPC_DONATION 0x001BEC00ULL // GlobalProgressionData NPC-donation/reward routine used by normal cat donations...

#define DATAOFF_LOCALIZATION_MANAGER 0x013B2590ULL // Global/static LocalizationManager object used for key-to-text lookups...
#define DATAOFF_MEWDIRECTOR_SINGLETON 0x013C7BD0ULL // Global MewDirector singleton pointer (Root access to director, scenes, and data managers)...
#define DATAOFF_HOUSE_BUTTON_TYPE_DESCRIPTOR 0x013E54F0ULL // Static HouseButton component type descriptor consumed by the engine allocator...
#define DATAOFF_HOUSE_CAT_VTABLE 0x00EEFE18ULL // HouseCat vtable address (Used as a runtime type check for scene components)...

#define OFF_HOUSE_STATUS_UI_SCENE_REF 0x18U // HouseStatusUI: Scene reference wrapper that leads back to the scene manager...
#define OFF_HOUSE_STATUS_UI_ROOT_NODE 0x48U // HouseStatusUI: Rroot UI node containing the reusable button node...
#define OFF_HOUSE_BUTTON_LABEL_TEXT 0x1B8U // HouseButton: Visible wide label text shown on the selector/button...
#define OFF_HOUSE_BUTTON_ROLE_NAME 0x1F8U // HouseButton: Narrow role name used by activation logic to distinguish buttons...
#define OFF_HOUSE_BUTTON_MANAGER 0x20U // HouseButton: Owning scene manager pointer used to validate cached custom buttons...
#define OFF_HOUSE_BUTTON_NODE 0x48U // HouseButton: UI node pointer used to validate cached custom buttons...

#define OFF_SCENE_REF_MANAGER 0x08U // SceneRef: Owning scene manager pointer...

#define OFF_MEWDIRECTOR_DIRECTOR 0x28U // MewDirector: Pointer containing the active scene vector...
#define OFF_MEWDIRECTOR_GLOBAL_PROGRESSION 0x5A8U // MewDirector: GlobalProgressionData pointer used for NPC donation reward progression...
#define OFF_SCENE_COMPONENT_LISTS 0x18U // Scene: Primary POD component-list pointer scanned for pickups and HouseCats...
#define OFF_SCENE_DOING_DESTRUCTION 0x4B0U // Scene/manager flag: Non-zero while destruction is in progress (Avoid mutating then)...
#define OFF_SCENE_NAME 0x4B8U // Scene: NarrowString scene name, used to find the "House" scene...
#define OFF_PICKUP_ITEM_RECORD 0x2D8U // Pickup component: Item-record pointer describing what the pickup represents...
#define OFF_PICKUP_ITEM_RECORD_KEY_STRING 0x08U // Item record: NarrowString key ("poop" identifies poop pickups)...
#define OFF_HOUSE_CAT_DEAD_BODY_COMPONENT 0xE8U // HouseCat: Dead-body scene object/component pointer checked before teardown...
#define OFF_HOUSE_CAT_ACTIVE_FLAG 0x88U // HouseCat active/enabled byte observed before safe teardown...

#define OFF_COMPONENT_CONTEXT 0x18U // Base component scene/context reference...
#define OFF_COMPONENT_MANAGER_HEADER 0x28U // I don't fucking know dude, I'm tired...
#define OFF_COMPONENT_FLAGS_A 0x0CU // HouseButton/component flag byte used by registration/setup buckets...
#define OFF_COMPONENT_FLAGS_B 0x0DU // HouseButton/component flag byte used by render-ish bucket setup...
#define OFF_COMPONENT_LAYER 0x0EU // Context layer/group byte copied from registered components...

#define OFF_CONTEXT_COMPONENT_REFS 0x20U // Context component-reference array starts here...
#define OFF_CONTEXT_LAYER 0x19U // Context layer/group byte used by registered components...

#define OFF_MANAGER_BUCKET_UPDATE_CAPACITY 0xD8U // Scene manager component-list bucket #1 capacity...
#define OFF_MANAGER_BUCKET_UPDATE_SIZE 0xDCU // Scene manager component-list bucket #1 size...
#define OFF_MANAGER_BUCKET_UPDATE_DATA 0xE0U // Scene manager component-list bucket #1 data pointer...

#define OFF_MANAGER_BUCKET_CLICK_CAPACITY 0x120U // Scene manager component-list bucket #2 capacity...
#define OFF_MANAGER_BUCKET_CLICK_SIZE 0x124U // Scene manager component-list bucket #2 size...
#define OFF_MANAGER_BUCKET_CLICK_DATA 0x128U // Scene manager component-list bucket #2 data pointer...

#define OFF_MANAGER_BUCKET_RENDER_CAPACITY 0x360U // Scene manager component-list bucket #3 capacity...
#define OFF_MANAGER_BUCKET_RENDER_SIZE 0x364U // Scene manager component-list bucket #3 size...
#define OFF_MANAGER_BUCKET_RENDER_DATA 0x368U // Scene manager component-list bucket #3 data pointer...

#define SIZE_HOUSE_BUTTON 0x3C0U // HouseButton instance size (Observed from construction/allocation path)...
#define SIZE_CALLBACK_BINDING_SCRATCH 0x40U // Temporary callback binding scratch expected by HouseButton setup...

#define COMPONENT_FLAGS_A_KEEP_SETUP_MASK 0xFCU
#define COMPONENT_FLAGS_A_SET_SETUP_MASK 0x04U
#define COMPONENT_FLAGS_A_CLICKABLE_MASK 0x08U
#define COMPONENT_FLAGS_A_POST_CLICK_MASK 0x0FU
#define COMPONENT_FLAGS_B_KEEP_RENDER_MASK 0xF8U
#define COMPONENT_FLAGS_B_SET_RENDER_MASK 0x08U
#define COMPONENT_FLAGS_B_POST_RENDER_MASK 0x8FU

#endif